name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  GO_VERSION: "1.21.4"
  GOFLAGS: -mod=readonly

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run vet
        run: make vet-all

      - name: Run lint
        run: make lint-all

      - name: Run unit tests
        run: make test-all
